[Extraction]
	#The Flux the Pumpjack requires each tick to pump, default=1024
	pumpjack_consumption = 10240
	#The amount of mB of oil a Pumpjack extracts per tick, default=15
	pumpjack_speed = 30

[Refining]
	#A modifier to apply to the energy costs of every Distillation Tower recipe, default=1
	distillationTower_energyModifier = 3.0

