
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true
	#Creates a debug folder inside your instance directory where all the dynamically generated resources will be saved
	save_debug_resources = false
	#Sends a packet to verify all dependencies mod versions are the same on connect. DIsable if it causes issues
	mod_version_check_packet = true
	#Don't touch unless you are told to
	debug_packet = false

	[general.tooltips]
		#Enabled tooltips showing which mod an EC item is from
		mod_origin_enabled = true
		#Enabled tooltips showing which block type an EC item is made from
		block_type_enabled = true
		#Only show on advanced settings
		show_on_advanced_tooltips = false

	#Disables certain types
	[general.types]

		[general.types.wood_type]

			[general.types.wood_type.iceandfire]
				dreadwood = true

			[general.types.wood_type.ars_nouveau]
				archwood = true

			[general.types.wood_type.aether]
				skyroot = true

			[general.types.wood_type.alexscaves]
				pewen = true
				thornwood = true

			[general.types.wood_type.biomesoplenty]
				fir = true
				redwood = true
				mahogany = true
				jacaranda = true
				palm = true
				willow = true
				dead = true
				magic = true
				umbran = true
				hellbark = true

			[general.types.wood_type.biomemakeover]
				blighted_balsa = true
				willow = true
				swamp_cypress = true
				ancient_oak = true

			[general.types.wood_type.snifferplus]
				stone_pine = true

			[general.types.wood_type.betterarcheology]
				rotten = true

			[general.types.wood_type.deeperdarker]
				echo = true

		[general.types.leaves_type]

			[general.types.leaves_type.ars_nouveau]
				blue_archwood = true
				green_archwood = true
				purple_archwood = true
				red_archwood = true

			[general.types.leaves_type.aether]
				skyroot = true
				golden_oak = true
				crystal = true
				crystal_fruit = true
				holiday = true
				decorated_holiday = true

			[general.types.leaves_type.alexscaves]
				ancient = true

			[general.types.leaves_type.biomesoplenty]
				origin = true
				flowering_oak = true
				maple = true
				orange_autumn = true
				yellow_autumn = true
				rainbow_birch = true
				snowblossom = true
				fir = true
				redwood = true
				mahogany = true
				jacaranda = true
				palm = true
				willow = true
				dead = true
				magic = true
				umbran = true
				hellbark = true

			[general.types.leaves_type.biomemakeover]
				blighted_balsa = true
				willow = true
				swamp_cypress = true
				ancient_oak = true

			[general.types.leaves_type.snifferplus]
				stone_pine = true

			[general.types.leaves_type.deeperdarker]
				echo = true

	#Disables specific entries
	[general.entries]

		[general.entries.wood_type]

			[general.entries.wood_type.farmersdelight]
				cabinet = true

